language: "node_js"

node_js:
  - "4"
  - "5"
  - "6"

install: npm

script:
  - "npm test"

notifications:
  email: false
  slack:
    rooms:
      - moeriki:Gqf2TnMQj95R0y9cNLQhw6Eo#updates
    on_success: change
    on_failure: always
